### ISSUE TITLE
Design the process of making custom texture packs (and skins too?) to be easy and modular.

### ISSUE THREAD

**Issue by Hunternif** [AntiqueAtlasTeam/AntiqueAtlas#16]

**Comment by Hunternif** [comment]
Tiles use texture sets exclusively, abolishing individual textures.

**Comment by Hunternif** [comment]
**DRAFT SOLUTION, WIP**

It would be nice to use String names instead of int IDs to identify Biomes, but inside Atlas a biome must be represented as a number internally, and there's no need to break backward compatibility of the configs.
**TODO find a way to use String names in configs.**

The following is a chain of biome texture configs order by increasing precedence:

1. The mod has its default texture config with 1) definitions of texture sets and 2) biomes assigned to texture sets. These files will be saved externally in json format as reference for modders, and also to let the player modify this config it manually. Deleting the files will cause them to be regenerated with default values.

2. Any world (SP or MP) may have its own set of the same configs, which will override defaults. Any calls to the API from other mods will only modify this config, and therefore must be called every time a new world is created. One use case for this may be if a texture may change depending on some condition that can change online. **TODO other mods shouldn't make redundant calls to the API. Will the need ever arise for modifying biome configs from their defaults at runtime?**

3. Any other mod or resource pack may have its own configs of this kind, which will override the default configs and world configs. **A resource pack may override existing textures?**
**TODO a resource pack may be plugged IN and OUT of any world.**

An identical chain should apply to marker configs.
Make sure config files are never physically overwritten, see #36.

**Comment by Faedelity** [comment]
I am very happy to see this is in process. I am quite willing to help test if that is useful. I am running primarily Minecraft 1.7.10, but I can make a profile for any version easily for testing purposes.

**Comment by tyra314** [comment]
This was superseded by the new resource pack based configuration: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/Resource-pack-based-Texture-Config
