### ISSUE TITLE
Custom TileEntity block that puts global markers in the map

### ISSUE THREAD

**Issue by Hunternif** [AntiqueAtlasTeam/AntiqueAtlas#32]
Mods that allow generating of structures from schematics (Fornivore's mod, Recurrent Complex, Schematics) can use this block to identify the structures on the map.

**Comment by tyra314** [comment]
Mods could use the API instead. In fact, there has been some mods doing this already (https://www.curseforge.com/minecraft/mc-mods/antique-waystones). I think this is the way.
