### ISSUE TITLE
config reading/writing issues

### ISSUE THREAD

**Issue by Hunternif** [AntiqueAtlasTeam/AntiqueAtlas#36]
Texture sets should only be checked for name (seeTextureSetMap)
Test custom configs extensively, make sure they are not overwritten (Golrith's issue)

**Comment by Hunternif** [comment]
Golrith proposes:
"
Perhaps go the EnderIO route with the json files (especially the biome allocations file). 

It has 2 jsons. One of defaults which the mod will update as required, and then a user overrides file, which the mod never touches.

It loads the defaults, then loads the overrides.
"

**Comment by Faedelity** [comment]
Sounds like a great solution. Probably a fair bit of coding to change this, which is very much appreciated.

**Comment by tyra314** [comment]
This is basically superseded by my current efforts to replace Tile / TextureSet / Texture with resource packs.
