### ISSUE TITLE
Fix the packet system

### ISSUE THREAD

**Issue by Hunternif** [AntiqueAtlasTeam/AntiqueAtlas#48]
Right now atlas data is being sent in a single packet via compressed NBT tag. This is stupid and dangerous, because atlas size may grow indefinitely.
- Don't send full NBT tag during synchronization.
- Make sure large atlases can be sent via multiple packets

**Comment by Hunternif** [comment]
I'd say this is one of the more important current issues

**Comment by Kenkron** [comment]
Man, this is a tricky one.  I'm guessing that, in order to fix this, the AtlasData object must no longer be a WorldSavedData object.  Instead, there should be a set of DimensionSubData and MarkerSubData objects, each of which store data for a particular atlas, at particular coordinates, of a particular dimension. Then something (probably a re-purposed AtlasDataHandler class) needs to hold a cache of these smaller objects as they are requested.

Does that sound about right?

**Comment by Hunternif** [comment]
I don't think it is strictly necessary to change the internal structure of AtlasData to do this. (Though i do think that it could and should be more sensibly organized somehow. Is the hash function for IntVec2 good enough? How about a Qtree or other geospatial data structures?)
I used to iterate through AtlasData tile by tile and send fixed-size packets as they fill up, so that after each packet a client's atlas could display the change (Areas would gradually fill in random places). But that was either slow or inelegant, I can't remember exactly why I abandoned that idea.
One way to do this could be to make a general-purpose large packet automatically split up into parts, which  are sent one by one and assembled on the client.
But your idea sounds interesting too.

**Comment by Hunternif** [comment]
(Having not worked on the mod for a long time, I may be forgetting something important here)
Please see issue #45, as it is connected to this one.

**Comment by Kenkron** [comment]
Splitting up a large packet into smaller ones sounds easier, but if a map is supposed to be able to grow to a very large size, it might be best to use only relavent regions.  I expect I'll make some mistakes implementing this, but I've got a new version of Ubuntu installed, and it's raining outside, so I'll give it a try.

**Comment by Kenkron** [comment]
I saw an image someone else had in their mod: ![java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097156bytes where max allowed: 2097152](https://camo.githubusercontent.com/ca0cca9568e914a75e8bc852492d56d2ba7913c7/687474703a2f2f692e6e656e746966792e6d652f6d7a4c6b566b466e2e706e67)

So the map really will have to be split up into smaller nbt packets. apex2top's message says: java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes, probably in reference to hunternif.mc.atlas.network.client.MapDataPacket, so splitting network packets really would help, but only until the map doubled again.

I must remember to have backwards compatible loading for seamless upgrading.

**Comment by Hunternif** [comment]
AFAIR in the beginning I sent map data via fixed-size packets, by
manually serializing all the tile coordinates into the buffer. And the only reason I switched to NBT was simply that I discovered this pre-existing method for sending NBT data, and it nicely decoupled the serialization code from the mod codebase. The switch was NOT a very good idea. @Kenkron, you don't have to stick to NBT if you see better ways to organize the data.

**Comment by Kenkron** [comment]
I think sticking to NBT, but just breaking it down is a good idea.  One of the implications of that note above is that, unless the NBT tag is broken up too, the maps will stop working when too large (about twice as large as the networking allows).

I've got a packet rework branch. It feels slow going, but I seem to be picking up speed as I learn more.

**Comment by Hunternif** [comment]
@Kenkron, I made an edit-typo in my comment: my switching to NBT was definitely NOT a good idea :)
Also, please check your inbox on Minecraft Forums.

**Comment by Kenkron** [comment]
oh, okay... I'll have to reconsider then.  I think the NBT may still need to be changed to avoid the the 2M limit, but I'll go check the minecraft-forum page.

**Comment by Hunternif** [comment]
Sorry for the confusion. I mean, I definitely made a mistake when I switched to NBT without considering packet size limit, which allowed this issue to arise. Your idea about breaking up the NBT will definitely work. I think it's a good way to solve this issue.

**Comment by Kenkron** [comment]
Oh, sweet.  Then I can keep at it.

**Comment by Sirse** [comment]
Temporary solution for 1.7.10 - https://github.com/gamerforEA/Minecraft-PacketUnlimiter
It will also works with newer versions, but you need to remap functions.

**Comment by Kenkron** [comment]
This looks cool.  I think there's an NBT tag size limit that will hit us at
twice the size of the network limit, but this might be able to buy some
time.

There's no readme. Is there any documentation on how it works?

**Comment by Sirse** [comment]
According to code - https://github.com/gamerforEA/Minecraft-PacketUnlimiter/blob/master/src/main/java/com/gamerforea/packetunlimiter/asm/PacketBufferPatch.java
- it splits oversized packet to 2 smaller packets with additional integer (istead short) and byte array.

I'm not tested it yet with AA, but it resolve my problem with oversized packet from other mod.

**Comment by Sirse** [comment]
Sry, previous message accedenctially removed(

**Comment by Kenkron** [comment]
>Sry, previous message accedenctially removed(

Lol, I wondered where it went.  If it weren't for email notifications, I wouldn't have seen it at all.  I guess I'll give it a look when I have time to scan someone else's source code.

TBH, I also haven't gotten around to making a world with an over-sized map.

**Comment by Sirse** [comment]
Also, maybe implement world's whitelist?
I need atlas only in overworld, but have many variuous world from other mods.

**Comment by Kenkron** [comment]
That's a good idea.  You should add a feature request issue for that.

**Comment by Kenkron** [comment]
There is a fix for this for 1.7.10 on curse. I'll close it once 1.8.9 and 1.9.4 also have the fix.

**Comment by Kenkron** [comment]
It's over.  I can finally move on to something more exciting!

**Comment by osipxd** [comment]
Also fixed #103

**Comment by Kenkron** [comment]
HOW?!!!!!!!

**Comment by Kenkron** [comment]
Forgot to clear the list of tile groups to send between each sending, defeating the entire purpose of the packet rework. This may have been causing #128.  Fixed as of 835eb51c928bbbfd8f50a0cc8743207f7dce4fe7.
