### ISSUE TITLE
Death markers not working

### ISSUE THREAD

**Issue by Hunternif** [AntiqueAtlasTeam/AntiqueAtlas#59]
> I have an Atlas in my inventory, and when I die there is no death marker in this atlas or in its clones.

**Comment by PureSpider** [comment]
This is still not working for me in the latest 1.7.10 version of the mod.

**Comment by Hunternif** [comment]
I can't reproduce this issue. @PureSpider, could you please test again in a fresh world running only AntiqueAtlas 4.2.10 - 1.7.10 and no other mods.

**Comment by Kenkron** [comment]
I can't reproduce this.
