### ISSUE TITLE
Markers can't really be deleted via API

### ISSUE THREAD

**Issue by Hunternif** [AntiqueAtlasTeam/AntiqueAtlas#69]
Because there's no way to get Marker ID solely via API.
Gotta carefully plan use cases.

**Comment by Hunternif** [comment]
putMarker() and putGlobalMarker() should rerturn int markerID.

**Comment by tyra314** [comment]
The API returns a `Marker` instance, which in turn knows the ID by `getID()`. So this should be fine.
