### ISSUE TITLE
Huge CPU usage on servers

### ISSUE THREAD

**Issue by Hunternif** [AntiqueAtlasTeam/AntiqueAtlas#74]
Just a heads up for anyone planning on using this mod for 1.7.10 Servers, this mod causes a huge CPU memory leak, seriously huge. CPU Usage spikes to 95% when idle, tested multiple times. Once the mod was removed, CPU usage went down to 1-3% when idle and 5% with about 20 players on. This was on the most recent 1.7.10 version, haven't tested the 1.8 version.
-- SlenderMiner @ Minecraft Forum

**Comment by Kenkron** [comment]
How long does it take the server to reach this point, and what configuration makes this bug occur? Did you have a lot of maps/markers/explored area/dimensions?  I've been trying to reproduce this bug, with forge 10.13.14.1558-1.7.10-universal and VisualVM's profiling tools, but with one player logged in, the heap has only shrunk over the course of an hour (from ~350Mb, to ~250Mb).  CPU usage has stayed around 3%.

**Comment by Hunternif** [comment]
Most of the newer issues I never personally verified. We may have to contact SlenderMiner for details.

**Comment by Kenkron** [comment]
Unable to reproduce bug.

**Comment by Hunternif** [comment]
have you tried having several players on? it could be done in debug mode by running several client apps on one machine.

**Comment by Kenkron** [comment]
I may have discovered this problem on a 1.7.10 server.

**Comment by Wavepon** [comment]
What causes this bug? Is it a bug that can be avoided on a smaller server, or completely unavoidable and game-breaking?

**Comment by Kenkron** [comment]
I'm working on an NBT format that stores the map in smaller segments on the packet rework branch.  It might be that updating a single large NBT tag takes a lot of work.  Then again, when you're working with a hammer, every problem looks like a nail. I'll check this bug again when I fix #48.

PS. When I ran into the bug, it would only slow down when you were holding the map. Go figure.

**Comment by tyra314** [comment]
The days of 1.17.10 are over. I think I can close that now.
