### ISSUE TITLE
Village markers don't work in custom modpack

### ISSUE THREAD

**Issue by Qohelethh** [AntiqueAtlasTeam/AntiqueAtlas#80]
I'm running a custom 1.7.10 modpack with Antique Atlas and a bunch of other mods, and despite the config setting being "B:auto_village_markers=true," the atlas does not create village markers. I can provide a full mod list if that is helpful, but the two main mods I would focus on first are Witchery and TerrainControl, since both change terrain generation.

I am using Forge 10.13.4.1614 and Antique Atlast 4.2.10.

**Comment by Kenkron** [comment]
These mods may change villages in such a way that the VillageWatcher class cannot see them.  Do the builings on the minimap also disappear, or is only the marker missing?

**Comment by Qohelethh** [comment]
The buildings on the minimap also disappear. It may not be possible to make them compatible.

**Comment by Hunternif** [comment]
Sorry for the super late response.
This sounds like a small issue that doesn't really break the gameplay. You can still place village markers manually.
