### ISSUE TITLE
File chooser dialog is unreliable

### ISSUE THREAD

**Issue by thecodewarrior** [AntiqueAtlasTeam/AntiqueAtlas#84]
The JFileChooser dialog is unreliable, sometimes it doesn't open at all. I think it has to do with threading weirdness, but I don't know.

**Comment by Kenkron** [comment]
Which OS/Java version are you using, and with how big of a map?

**Comment by thecodewarrior** [comment]
I'm on OS X Yosemite running Java 8

**Comment by Hunternif** [comment]
We could save the exported image in `.minecraft` under some default name, which would be unique to the world + atlas instance.

Not strictly related to this, but there's an old bug that the exporting screen would close if you resize the screen while exporting. Or has that been fixed already?
https://github.com/Hunternif/AntiqueAtlas/blob/master/src/main/java/hunternif/mc/atlas/client/gui/GuiAtlas.java#L366

Finally, I'm just so happy to see you guys continue this mod. Cheers! :+1: :+1: :+1:

**Comment by esotericist** [comment]
I know this is a rather old issue, but I'm still experiencing this problem.

A way of simply exporting directly to a file without a chooser -- possibly similar to how screenshots are named -- would be very helpful.

Edit: to be clear, what happens is I click 'export' and it never actually appears. This is on Windows (also java 8).

**Comment by esotericist** [comment]
As a further update, even with just a minimal instance -- forge 2705, Antique Atlas 1.12.2-4.4.9 -- the file chooser can fail to appear immediately after a new world (and atlas) is made.

**Comment by tyra314** [comment]
I merged #196. The method is still in the code, so we could add an option, but as this issue probably persists then, I'd opt for just closing this issue now.
