### ISSUE TITLE
Missing Biome: Birch Forest Hills M

### ISSUE THREAD

**Issue by Kenkron** [AntiqueAtlasTeam/AntiqueAtlas#91]
There appears not to be a birch like texture for birch forest hills m.

**Comment by mostlyfabulous** [comment]
I checked the texture pack and would those not match: tall_birch_hills & tall_birch_hills2?

**Comment by Kenkron** [comment]
I'll have to double check.

**Comment by Hunternif** [comment]
This should be it: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/blob/d73f8930d5ed75822cf9d02c3eba87c88e492b0d/src/main/java/hunternif/mc/atlas/ClientProxy.java#L274
