### ISSUE TITLE
Markers cannot be reloaded in-game if placed on the map

### ISSUE THREAD

**Issue by Zsashas** [AntiqueAtlasTeam/AntiqueAtlas#95]
I managed to get the custom markers working, however some didn't look quite right. Decided to edit some to fix this. Apologies for the incoming wall of text.

Series of events:

Last night:
1: Copied the marker files and edited them
2: Attempted to re-add the files to the resource pack
3: Since the pack was in use, I went and disabled it in-game, so I could add the files then re-enable it. However, it said it was still in use.
4: Shut down Minecraft completely, re-add files to the pack.

This morning:
5: Load up MC, load up world.
6: Notice most map markers placed are the purple/black missing texture square, remember that last night I disabled the marker pack.
7: Re-enable the pack. Markers, other than default ones, are still the purple/black square.
8: Place a new marker to look at the list. Only markers that had been placed on my atlas somewhere when the pack was disabled and re-enabled are missing textures. All others are fine.

**Conclusion**:
 Antique Atlas cannot reload textures for markers if reloaded via resource pack menu in-game if they are currently placed on the map at least once.

**Comment by tyra314** [comment]
The marker config changed with the 6.0.0 release. As there probably won't be updates for older Minecraft versions. I think this is "fixed" now.
