### ISSUE TITLE
Unable to login when unlocked huge areas of the map

### ISSUE THREAD

**Issue by apex2top** [AntiqueAtlasTeam/AntiqueAtlas#98]
Hey, i was flying around in my world and unlocked a huge part of the map. After a relog the server did not let me in, because of this exception:

NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes

-----
After I deleted the aAtlas-Data on the server i could login again. So I lost all my uncovered area.

**Comment by Kenkron** [comment]
This is another issue stemming from #48 

I'll get to a fix as soon as I can.
